
@hostname = http://localhost:3000/
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}



###
GET  http://localhost:3000/products.json


###
GET  http://localhost:3000/products/1.json


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "name",
  "price": "price",
  "image_url": "url",
  "description": "description"
}

###
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": "funny dog plush",
  "price": 4,
  "image_url": "https://www.squishable.com/mm5/graphics/00000001/mini_squish_dachshund_hot_dog_7.jpg",
  "description": "woah!"
}

###
DELETE http://localhost:3000/products/7.json


###
GET http://localhost:3000/products/1.json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

### Orders test
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyNzkyNTV9.mH5Kt7A3sNjvwhOUxRijOrbGtEXJ9GvXjLC-QCTApLY
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 1,
}

### Orders test
GET http://localhost:3000/orders.json



###
